apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.portSetting }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .NodePort }}
  {{- end }}
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
