apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: quality
  namespace: argocd
spec: 
  destination: 
    namespace: ci
    server: "https://kubernetes.default.svc"
  project: quality
  source: 
    path: sonarqube
    repoURL: "https://github.com/AdilNehal/DevOPs-GitOPs-Workflow.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true