kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "prometheus.server.fullname" . }}
  labels: {{- include "prometheus.server.labels" . | nindent 4 }}
  {{- if .Values.server.persistentVolume.annotations }}
  annotations:
    {{- range $key, $value := .Values.server.persistentVolume.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.server.persistentVolume.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistentVolume.size | quote }}
  {{- if .Values.server.persistentVolume.storageClass }}
  {{- if (eq "-" .Values.server.persistentVolume.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.server.persistentVolume.storageClass }}"
  {{- end }}
  {{- end }}
  volumeName: {{ template "prometheus.server.fullname" . }}-pv