#SPDX-License-Identifier: MIT-0
---
# tasks file for components
- name: Ensure Kubernetes cluster is up & running
  block:
    - name: Check if the Kubernetes cluster is up & running
      command: kubectl cluster-info
      register: cluster_info
      failed_when: cluster_info.rc != 0

  rescue:
    - name: Print error message
      debug:
        msg: "Kubernetes cluster is not running. Exiting the role."

    - name: Fail the play
      fail:
        msg: "Kubernetes cluster check failed. Stopping role execution."

- name: Installing Sonarqube via local Helm Chart
  block:
    - name: Install Sonarqube using local Helm chart and custom values
      command: >
        helm install quality /home/adiln/repos/DevOPs-GitOPs-Workflow/sonarqube --namespace ci
      register: helm_install_sonarqube
      failed_when: helm_install_sonarqube.rc != 0

  rescue:
    - name: Print error message for Sonarqube installation failure
      debug:
        msg: "Sonarqube installation from local chart failed. Exiting the role."

    - name: Fail the play for Sonarqube installation failure
      fail:
        msg: "Sonarqube installation from local chart failed. Stopping role execution."

