#SPDX-License-Identifier: MIT-0
---
# tasks file for components
- name: Ensure Kubernetes cluster is up & running
  block:
    - name: Check if the Kubernetes cluster is up & running
      command: kubectl cluster-info
      register: cluster_info
      failed_when: cluster_info.rc != 0

  rescue:
    - name: Print error message
      debug:
        msg: "Kubernetes cluster is not running. Exiting the role."

    - name: Fail the play
      fail:
        msg: "Kubernetes cluster check failed. Stopping role execution."

- name: Installing Sonarqube via local Helm Chart
  block:
    - name: Install Sonarqube using local Helm chart and custom values
      command: >
        helm install quality /home/adiln/repos/DevOPs-GitOPs-Workflow/sonarqube --namespace ci
      register: helm_install_sonarqube
      failed_when: helm_install_sonarqube.rc != 0

  rescue:
    - name: Print error message for Sonarqube installation failure
      debug:
        msg: "Sonarqube installation from local chart failed. Exiting the role."

    - name: Fail the play for Sonarqube installation failure
      fail:
        msg: "Sonarqube installation from local chart failed. Stopping role execution."

- name: Installing Prometheus Stack via local Helm Chart
  block:
    - name: Install Prometheus Stack using local Helm chart and custom values
      command: >
        helm install monitoring /home/adiln/repos/DevOPs-GitOPs-Workflow/kube-prometheus-stack --namespace monitoring
      register: helm_install_prometheus_stack
      failed_when: helm_install_prometheus_stack.rc != 0

  rescue:
    - name: Print error message for Prometheus Stack installation failure
      debug:
        msg: "Prometheus Stack installation from local chart failed. Exiting the role."

    - name: Fail the play for Prometheus Stack installation failure
      fail:
        msg: "Prometheus Stack installation from local chart failed. Stopping role execution

- name: Apply ArgoCD CRDs using kubectl kustomize
  command: >
    kubectl apply -n cd -k https://github.com/argoproj/argo-cd/manifests/crds?ref=stable
  register: apply_argocd_crds
  failed_when: apply_argocd_crds.rc != 0

  rescue:
    - name: Print error message for ArgoCD installation failure
      debug:
        msg: "ArgoCD installation from kustomize failed. Exiting the role."

    - name: Fail the play for ArgoCD installation failure
      fail:
        msg: "ArgoCD installation from kustomize failed. Stopping role execution."

- name: Install KEDA via Helm with error handling
  block:
    - name: Add KEDA Helm repo
      command: helm repo add kedacore https://kedacore.github.io/charts
      register: add_keda_repo
      failed_when: add_keda_repo.rc != 0

    - name: Update Helm repositories
      command: helm repo update
      register: update_helm_repos
      failed_when: update_helm_repos.rc != 0

    - name: Install KEDA via Helm chart
      command: >
        helm install keda kedacore/keda --namespace keda --create-namespace
      register: install_keda
      failed_when: install_keda.rc != 0

  rescue:
    - name: Print failure message for KEDA installation
      debug:
        msg: "Failed to install KEDA. Check Helm repo, internet connectivity, or cluster access."

    - name: Show Helm repo add command result (for debugging)
      debug:
        var: add_keda_repo

    - name: Show Helm repo update result (for debugging)
      debug:
        var: update_helm_repos

    - name: Show Helm install result (for debugging)
      debug:
        var: install_keda

