apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.fullname" . }}-credentials
  namespace: {{ .Values.StatefulSet.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  elastic: {{ .Values.auth.elasticPassword | quote }}