apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-headless
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.headless }}
  ports:
    - port: {{ .Values.service.port_rest }}
      name: {{ .Values.service.name_rest }}
    - port: {{ .Values.service.port_inner }}
      name: {{ .Values.service.name_inner }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
