apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    helm.sh/chart: {{ include "elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.StatefulSet.replicas }}
  serviceName: {{ .Values.StatefulSet.serviceName }}-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "elasticsearch.fullname" . }}
          image: "{{ .Values.StatefulSet.image.repository }}:{{ .Values.StatefulSet.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.StatefulSet.resources | nindent 12 }}
          ports:
            {{- range .Values.StatefulSet.portsSettings }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
          {{- if hasKey .Values.StatefulSet "livenessProbe" }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if hasKey .Values.StatefulSet "readinessProbe" }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if hasKey .Values.StatefulSet "volumeMounts" }}
          volumeMounts:
            {{- toYaml .Values.StatefulSet.volumeMounts | nindent 12 }}
          {{- end }}
          env: 
            {{- range .Values.StatefulSet.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      initContainers:
        {{- range .Values.StatefulSet.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command: {{ .command }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "elasticsearch.labels" . | nindent 8 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.StatefulSet.volumeClaimTemplates.resources.requests.storage }}