apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: quality
  namespace: argocd
spec:
  description: Sonarqube ArgoCD project.
  sourceRepos: 
    - "*"
  destinations:
    - namespace: ci
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"