apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: node-app
  namespace: argocd
spec: 
  destination: 
    namespace: demo
    server: "https://kubernetes.default.svc"
  project: project1
  source: 
    path: helm-charts-deploy/node-app
    repoURL: "https://github.com/AdilNehal/Nodejs-Workflow-ArgoCD.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true