kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "alertmanager.fullname" . }}-pv
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- range $key, $value := .Values.persistence.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Important: empty means no dynamic provisioning is expected
  hostPath:
    path: {{ .Values.persistence.mountPath }}